Update update-m3u.yml

diff --git a/.github/workflows/update-m3u.yml b/.github/workflows/update-m3u.yml
--- a/.github/workflows/update-m3u.yml
+++ b/.github/workflows/update-m3u.yml
@@ -11,7 +11,7 @@ jobs:
 
     steps:
     - name: Checkout repository
-      uses: actions/checkout@v2
+      uses: actions/checkout@v3
 
     - name: Fetch M3U files
       run: |
@@ -23,9 +23,11 @@ jobs:
         cat IPV6.m3u IPTV.m3u > combined_iptv.txt
 
     - name: Commit and push changes
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
         git config --global user.name 'github-actions[bot]'
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
         git add combined_iptv.txt
-        git commit -m 'Update combined_iptv.txt'
-        git push --force
+        git commit -m 'Update combined_iptv.txt' || echo "No changes to commit"
+        git push || echo "Push failed"
